# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ciberchico420
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test-lambda-docs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-test

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    AUTODOCS_BRANCH: main
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:us-east-1:435461726783:table/dynamicDocs

custom:
  auto-docs:
    name: "Serverless Test"
    description: "This is a test for the Serverless Framework Auto Docs plugin."
    version: "1.0.0"
    outputDir: "docs"
    linkerRoute: https://7lqn0bxcch.execute-api.us-east-1.amazonaws.com/proxy

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

  bye:
    handler: src/handlers/handler.bye
    events:
      - httpApi:
          path: /bye
          method: get

  proxy:
    handler: src/handlers/handler.proxy
    events:
      - httpApi:
          path: /proxy/{proxy+}
          method: any
    environment:
      LINKER_TABLE_NAME: dynamicDocs

plugins:
  - "@auto-docs/serverless-dynamic"
