# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ciberchico420
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test-lambda-docs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-test

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - "../packages/serverless/dist/index.js"
